language: cpp
compiler:
- g++

before_install:
- sudo apt-get install automake -y
- sudo apt-get install autoconf -y
 
script: 
- aclocal
- autoconf -v 
- autoconf
- ./configure && make 
