language: cpp
compiler:
- g++

before_install:
- sudo apt-get install automake -y
- sudo apt-get install autoconf -y
 
script: 
- automake --version
- autoconf -V 
- aclocal
- autoconf
- ./configure && make 
